valentina/app/urls.py
from django.conf.urls import url
from valentina.app.views import (welcome, chat, profile, facebook, report,
                                 create_affiliation, list_affiliations,
                                 chat_preferences, logout)

urlpatterns = [
    url(r'^$', welcome, name='welcome'),
    url(r'^chat/preferences/$', chat_preferences, name='preferences'),
    url(r'^chat/(?P<hash_id>[\d\w]+)/$', chat, name='chat'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^facebook/$', facebook, name='facebook'),
    url(r'^join/$', create_affiliation, name='affiliation'),
    url(r'^chats/$', list_affiliations, name='affiliations'),
    url(r'^report/$', report, name='report'),
    url(r'^logout/$', logout, name='logout'),
]

valentina/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from valentina.home.views import home, blocked, female_only

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^oauth/', include('social.apps.django_app.urls', namespace='oauth')),
    url(r'^app/', include('valentina.app.urls', namespace='app')),
    url(r'^blocked/$', blocked, name='blocked'),
    url(r'^exclusive/$', female_only, name='female_only'),
    url(r'^admin/', admin.site.urls),
]

valentina/home/models.py
from django.db import models

# Create your models here.

valentina/home/views.py
from django.contrib.auth import logout
from django.shortcuts import redirect, render, resolve_url


def home(request):
    if request.user.is_authenticated():
        return redirect(resolve_url('app:welcome'))
    return render(request, 'home/home.html')


def blocked(request):
    logout(request)
    return render(request, 'home/blocked.html')


def female_only(request):
    logout(request)
    return render(request, 'home/female_only.html')

valentina/app/templates/app/home.html
{% load static from staticfiles %}<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% load static from staticfiles %}
    {% load compress %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>{% block title %}Valentina{% endblock %}</title>

    {% compress css %}
    <link rel="stylesheet" type="text/x-sass" href="{% static 'css/app.sass' %}">
    {% endcompress %}

    {% include 'favicons.html' %}

  </head>
  <body>

    <main class="col{% if not nickname %} first_access{% endif %}">
      
      <nav class="app">
        <div>
          <h1>{% include 'home/svg/valentina.svg' %}</h1>
          <ul>
            <li><a href="#" id="preferences"  title="Preferências">{% include 'app/svg/preferences.svg' %}</a></li>
            <li><a href="{% url 'app:logout' %}" title="Sair">{% include 'app/svg/logout.svg' %}</a></li>
          </ul>
        </div>
      </nav><!-- end nav.app -->
      
      <form class="preferences" action="{% url 'app:profile' %}" method="post">
        <h3>Preferências</h3>
        <p>
          <span>Aqui você é conhecida como</span>
          <input name="nickname" type="text" value="{% firstof nickname random_nickname %}"> 
        </p>
        <p>
          <button type="reset">Cancelar</button>
          <button type="submit">Salvar</button>
        </p>
      </form>

      <nav id="chat_list" data-search-url="{% url 'app:facebook' %}" data-join-url="{% url 'app:affiliation' %}" data-facebook="{% static 'img/facebook.svg' %}" data-magnifier="{% static 'img/magnifier.svg' %}"></nav>

      <footer>
        <ul>
          <li><a href="#">Termos de Uso &amp; Privacidade</a></li>
          <li><a href="#">Contato</a></li>
        </ul>
      </footer>

    </main>

    <div id="chat_panels" data-report="{% static 'img/report.svg' %}"></div>

    {% compress js %}
    <script async type="text/x-babel" src="{% static 'js/app.js' %}"></script> 
    {% endcompress %}

  </body>
</html>